import { reactive } from 'vue';
export function useForm() {
    const form = reactive({
        control_no: '',
        qr_code: '',
        acct_person: '',
        sex: '',
        employmentType: '',
        brand: '',
        model: '',
        property_no: '',
        serial_no: '',
        acquisition_cost: 0,
        processor: '',
        division_id: '',
        acct_person_division_id: '',
        selectedDivision: '',
        selectedAcctDivision: '',
        selectedActualDivision: '',
        selectedWorkNature: '',
        selectedSection: '',
        selectedRangeCategory: '',
        selectedEquipmentType: '',
        actual_user: '',
        remarks: '',
        year_acquired: '',
        shelf_life: '',
        status: '',
        source_div: '',
        target_div: '',
    });
    const specs_form = reactive({
        specs_processor: '',
        specs_ram_capacity: '',
        specs_hdd: 0,
        specs_hdd_capacity: '',
        specs_ram: '',
        specs_gpu: 0, // Ensure this is a number
        specs_ssd: 0,
        specs_ssd_capacity: '',
        specs_gpu_dedic_info: '',
        specs_net: null,
        specs_net_iswireless: '',
    });
    const software_form = reactive({
        operating_system: '',
        ms_office: '',
        arcgis: '',
        adobe_pdf: '',
        adobe_photoshop: '',
        autocad: '',
    });
    const peripheral_form = reactive({
        monitor1QrCode: '',
        monitor1BrandModel: '',
        monitor1Model: '',
        monitor1SerialNumber: '',
        monitor1PropertyNumber: '',
        monitor1AccountPersonInPN: '',
        monitor1ActualUser: '',
        monitor1Status: '',
        monitor2QrCode: '',
        monitor2BrandModel: '',
        monitor2Model: '',
        monitor2SerialNumber: '',
        monitor2PropertyNumber: '',
        monitor2AccountPersonInPN: '',
        monitor2ActualUser: '',
        monitor2Status: '',
        ups_qr_code: '',
        ups_brand: '',
        ups_model: '',
        ups_serial_no: '',
        ups_property_no: '',
        ups_accountPersonInPN: '',
        ups_qr_acctual_user: '',
        ups_status: '',
        mon1division1: '',
        mon1division2: '',
        division_id: '',
    });
    const um_create_form = reactive({
        region: 'REGION IV-A (CALABARZON)',
        roles: '',
        role_id: '',
        geo_code: '',
        province: '',
        province_c: '',
        city_mun: '',
        city_mun_c: '',
        first_name: '',
        middle_name: '',
        last_name: '',
        complete_address: '',
        employment_status: '',
        designation: '',
        sex: '',
        mobile_no: '',
        division: '',
        division_id: '',
        position: '',
        email: '',
        contact_details: '',
        username: '',
        password: '',
    });
    return { form, specs_form, software_form, peripheral_form, um_create_form };
}
